CREATE TABLE farms (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120)   NOT NULL,
    total_area_ha NUMERIC(12, 2) NOT NULL,
    city          VARCHAR(120),
    state         VARCHAR(2),
    user_id       BIGINT         NOT NULL,
    created_at    TIMESTAMPTZ    NOT NULL,
    updated_at    TIMESTAMPTZ    NOT NULL,
    CONSTRAINT fk_farms_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_farms_total_area CHECK (total_area_ha > 0)
);

CREATE INDEX idx_farms_user_id ON farms (user_id);
CREATE INDEX idx_farms_user_id_name ON farms (user_id, name);
