CREATE TABLE fields (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120)   NOT NULL,
    area_ha    NUMERIC(12, 2) NOT NULL,
    soil_type  VARCHAR(60),
    farm_id    BIGINT         NOT NULL,
    created_at TIMESTAMPTZ    NOT NULL,
    updated_at TIMESTAMPTZ    NOT NULL,
    CONSTRAINT fk_fields_farm FOREIGN KEY (farm_id) REFERENCES farms (id),
    CONSTRAINT chk_fields_area CHECK (area_ha > 0)
);

CREATE INDEX idx_fields_farm_id ON fields (farm_id);
