CREATE TABLE crops (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120) NOT NULL,
    type          VARCHAR(60)  NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    planting_date DATE,
    harvest_date  DATE,
    field_id      BIGINT       NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_crops_field FOREIGN KEY (field_id) REFERENCES fields (id),
    CONSTRAINT chk_crops_status CHECK (status IN ('PLANNED', 'PLANTED', 'HARVESTED'))
);

CREATE INDEX idx_crops_field_id ON crops (field_id);
